# Generated by Django 4.2.11 on 2024-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images')),
                ('sceintific_name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=3)),
            ],
        ),
    ]
